#ifndef _QEMU_MIPS_REG_H_
#define _QEMU_MIPS_REG_H_

#define QEMU_MIPS_UART0ADR	0x140003f8ul
#define QEMU_MIPS_UART0SIZE	0x100

#define PLATFORM_COUNTER_FREQ	MIPS_DEFAULT_HZ

#endif /* _QEMU_MIPS_REG_H_ */
